- name: playbook
  hosts: all
  become: true

  tasks:      
    - name: update ubuntu
      apt:
        update_cache: true

    - name: remove  git 
      apt:
        name: git
        state: absent
      tags: a

    - name: remove tree
      apt:
        name: tree
        state: absent
      tags: b
